version: "3.9"

services:

  perlite:
    image: sec77/perlite:latest
    container_name: perlite
          
    environment:
      - NOTES_PATH=Demo
      - HIDE_FOLDERS=docs,private,trash

    volumes:
      - ./perlite:/var/www/perlite
      - ./Demo:/var/www/perlite/Demo:ro

  web:
    build:
        context: ./web
    container_name: web      
    ports:
      - 80:80 
    volumes:
      - ./perlite:/var/www/perlite
      - ./Demo:/var/www/perlite/Demo:ro   
    depends_on:
      - perlite

