version: "3.9"

services:
  perlite:
    image: sec77/perlite:latest
    container_name: perlite
    environment:
      - NOTES_PATH=Demo
      - LINE_BREAKS=true
      - HIDE_FOLDERS=docs,private,trash
      - ALLOWED_FILE_LINK_TYPES=pdf
      - DISABLE_POP_HOVER=true
      - SHOW_TOC=true
      - HOME_FILE=README
      - FONT_SIZE=15
    volumes:
      - ./perlite:/var/www/perlite
      - ./perlite/Demo:/var/www/perlite/Demo:ro

  web:
    build:
        context: ./web
    image: sec77/perlite_web:stable
    container_name: perlite_web-dev      
    ports:
      - 8090:80 
    volumes:
      - ./perlite:/var/www/perlite
      - ./perlite/Demo:/var/www/perlite/Demo:ro   
    depends_on:
      - perlite

