version: "3.9"

services:
  perlite:
    image: sec77/perlite:latest
    container_name: perlite-dev
    environment:
      - NOTES_PATH=Demo
      # - NOTES_PATH=_Notes
      - HIDE_FOLDERS=docs,private,trash
    volumes:
      - ./perlite:/var/www/perlite
      - ./Demo:/var/www/perlite/Demo:ro
      # - ./_Notes:/var/www/perlite/_Notes:ro

  web:
    build:
        context: ./web
    image: sec77/perlite_web:stable
    container_name: perlite_web-dev      
    ports:
      - 80:80 
    volumes:
      - ./perlite:/var/www/perlite
      - ./Demo:/var/www/perlite/Demo:ro   
      # - ./_Notes:/var/www/perlite/_Notes:ro   
    depends_on:
      - perlite

