version: "3.9"

services:
  perlite:
    image: sec77/perlite:1.4.4
    container_name: perlite
    restart: unless-stopped
    environment:
      - NOTES_PATH=Demo
      - HIDE_FOLDERS=docs,private,trash
    volumes:
      - ./Demo:/var/www/perlite/Demo:ro

  web:
    build:
        context: ./web
    image: sec77/perlite_web:stable
    container_name: perlite_web
    restart: unless-stopped
    ports:
      - 80:80
    volumes_from: 
      - perlite       
    depends_on:
      - perlite

