version: "3.9"

services:
  perlite:
    image: sec77/perlite:latest
    container_name: perlite-build
    environment:
      - NOTES_PATH=Demo
      - HIDE_FOLDERS=docs,private,trash
      - LINE_BREAKS=true
      - ALLOWED_FILE_LINK_TYPES=pdf
      - DISABLE_POP_HOVER=true
      - SHOW_TOC=true
      - HOME_FILE=README
      - FONT_SIZE=15
      - HTML_SAFE_MODE=true
      - TEMP_PATH=/tmp
      - SITE_TITLE=Demo
      - SITE_TYPE=article
      - SITE_URL=
      - SITE_IMAGE=
      - SITE_DESC=
      - SITE_NAME=
      - SITE_TWITTER=
    volumes:
      - ./perlite:/var/www/perlite
      - ./perlite/Demo:/var/www/perlite/Demo:ro

  web:
    build:
        context: ./web
    image: sec77/perlite_web:stable
    container_name: perlite_web-build      
    ports:
      - 80:80 
    volumes:
      - ./perlite:/var/www/perlite
      - ./perlite/Demo:/var/www/perlite/Demo:ro   
    depends_on:
      - perlite

